// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about-us" | "/account" | "/account/offers" | "/account/orders" | "/account/orders/[id]" | "/account/orders/[id]/review" | "/account/profile" | "/admin" | "/admin/analytics" | "/admin/coupons" | "/admin/enquiries" | "/admin/homepage" | "/admin/homepage/promotions" | "/admin/live-chat" | "/admin/login" | "/admin/orders" | "/admin/orders/[id]" | "/admin/products" | "/admin/products/[id]" | "/admin/products/new" | "/admin/reviews" | "/admin/settings" | "/admin/templates" | "/blog" | "/canvasfix01-test" | "/cart" | "/checkout" | "/contact" | "/cookie-policy" | "/design" | "/design/preview" | "/faq" | "/forgot-password" | "/offers" | "/offers/[slug]" | "/order-success" | "/payment" | "/policies" | "/previous-home" | "/privacy-policy" | "/products" | "/products/[id]" | "/refund-returns-policy" | "/reset-password" | "/shipping-policy" | "/sign-in" | "/sign-up" | "/sitemap" | "/terms-of-service" | "/upload-artwork" | "/warranty-disclaimer"
type AppRouteHandlerRoutes = "/api/account/addresses" | "/api/account/addresses/[id]" | "/api/account/profile" | "/api/admin-auth/[...auth]" | "/api/admin/activity" | "/api/admin/analytics" | "/api/admin/analytics/export" | "/api/admin/categories" | "/api/admin/categories/[id]" | "/api/admin/coupons" | "/api/admin/coupons/[id]" | "/api/admin/enquiries" | "/api/admin/enquiries/[id]" | "/api/admin/heroes" | "/api/admin/heroes/[id]" | "/api/admin/live-chat" | "/api/admin/offers" | "/api/admin/offers/[id]" | "/api/admin/orders/[id]" | "/api/admin/orders/[id]/items/[itemId]/production" | "/api/admin/products" | "/api/admin/products/[id]" | "/api/admin/promotions" | "/api/admin/promotions/[id]" | "/api/admin/reviews" | "/api/admin/reviews/[id]" | "/api/admin/settings" | "/api/admin/templates" | "/api/admin/templates/[id]" | "/api/admin/templates/source" | "/api/admin/uploads" | "/api/artwork" | "/api/artwork/preview" | "/api/auth/[...auth]" | "/api/contact" | "/api/coupons/validate" | "/api/cron/coupon-reservations" | "/api/designs" | "/api/designs/[id]/preview" | "/api/designs/draft" | "/api/live-chat" | "/api/navigation" | "/api/offers" | "/api/orders" | "/api/orders/[id]" | "/api/orders/[id]/receipt" | "/api/payments/attempt" | "/api/payments/intent" | "/api/payments/webhook" | "/api/products" | "/api/products/[id]" | "/api/reviews" | "/api/store/settings" | "/api/templates" | "/api/templates/[id]" | "/api/templates/[id]/editor-data" | "/api/uploads/presign"
type PageRoutes = never
type LayoutRoutes = "/" | "/offers"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about-us": {}
  "/account": {}
  "/account/offers": {}
  "/account/orders": {}
  "/account/orders/[id]": { "id": string; }
  "/account/orders/[id]/review": { "id": string; }
  "/account/profile": {}
  "/admin": {}
  "/admin/analytics": {}
  "/admin/coupons": {}
  "/admin/enquiries": {}
  "/admin/homepage": {}
  "/admin/homepage/promotions": {}
  "/admin/live-chat": {}
  "/admin/login": {}
  "/admin/orders": {}
  "/admin/orders/[id]": { "id": string; }
  "/admin/products": {}
  "/admin/products/[id]": { "id": string; }
  "/admin/products/new": {}
  "/admin/reviews": {}
  "/admin/settings": {}
  "/admin/templates": {}
  "/api/account/addresses": {}
  "/api/account/addresses/[id]": { "id": string; }
  "/api/account/profile": {}
  "/api/admin-auth/[...auth]": { "auth": string[]; }
  "/api/admin/activity": {}
  "/api/admin/analytics": {}
  "/api/admin/analytics/export": {}
  "/api/admin/categories": {}
  "/api/admin/categories/[id]": { "id": string; }
  "/api/admin/coupons": {}
  "/api/admin/coupons/[id]": { "id": string; }
  "/api/admin/enquiries": {}
  "/api/admin/enquiries/[id]": { "id": string; }
  "/api/admin/heroes": {}
  "/api/admin/heroes/[id]": { "id": string; }
  "/api/admin/live-chat": {}
  "/api/admin/offers": {}
  "/api/admin/offers/[id]": { "id": string; }
  "/api/admin/orders/[id]": { "id": string; }
  "/api/admin/orders/[id]/items/[itemId]/production": { "id": string; "itemId": string; }
  "/api/admin/products": {}
  "/api/admin/products/[id]": { "id": string; }
  "/api/admin/promotions": {}
  "/api/admin/promotions/[id]": { "id": string; }
  "/api/admin/reviews": {}
  "/api/admin/reviews/[id]": { "id": string; }
  "/api/admin/settings": {}
  "/api/admin/templates": {}
  "/api/admin/templates/[id]": { "id": string; }
  "/api/admin/templates/source": {}
  "/api/admin/uploads": {}
  "/api/artwork": {}
  "/api/artwork/preview": {}
  "/api/auth/[...auth]": { "auth": string[]; }
  "/api/contact": {}
  "/api/coupons/validate": {}
  "/api/cron/coupon-reservations": {}
  "/api/designs": {}
  "/api/designs/[id]/preview": { "id": string; }
  "/api/designs/draft": {}
  "/api/live-chat": {}
  "/api/navigation": {}
  "/api/offers": {}
  "/api/orders": {}
  "/api/orders/[id]": { "id": string; }
  "/api/orders/[id]/receipt": { "id": string; }
  "/api/payments/attempt": {}
  "/api/payments/intent": {}
  "/api/payments/webhook": {}
  "/api/products": {}
  "/api/products/[id]": { "id": string; }
  "/api/reviews": {}
  "/api/store/settings": {}
  "/api/templates": {}
  "/api/templates/[id]": { "id": string; }
  "/api/templates/[id]/editor-data": { "id": string; }
  "/api/uploads/presign": {}
  "/blog": {}
  "/canvasfix01-test": {}
  "/cart": {}
  "/checkout": {}
  "/contact": {}
  "/cookie-policy": {}
  "/design": {}
  "/design/preview": {}
  "/faq": {}
  "/forgot-password": {}
  "/offers": {}
  "/offers/[slug]": { "slug": string; }
  "/order-success": {}
  "/payment": {}
  "/policies": {}
  "/previous-home": {}
  "/privacy-policy": {}
  "/products": {}
  "/products/[id]": { "id": string; }
  "/refund-returns-policy": {}
  "/reset-password": {}
  "/shipping-policy": {}
  "/sign-in": {}
  "/sign-up": {}
  "/sitemap": {}
  "/terms-of-service": {}
  "/upload-artwork": {}
  "/warranty-disclaimer": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/offers": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
