'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { ArrowLeft, CheckCircle2, Save, XCircle } from 'lucide-react'
import { useAdminSession } from '@/lib/admin-auth-client'
import { adminPath } from '@/lib/auth/admin-path'
import { getUserRole } from '@/lib/auth/roles'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'

interface Settings { storeName: string; storeEmail: string; storePhone: string; address: string; currency: string; taxRate: number | string; shippingCost: number | string; freeShippingThreshold: number | string; turnaroundDays: string; footerText: string; termsUrl: string; privacyUrl: string; allowGuestCheckout: boolean; paymentTestMode: boolean }
interface Configuration { storage: { provider: string; configured: boolean }; payments: { testMode: boolean; stripeConfigured: boolean; paypalConfigured: boolean } }
const initial: Settings = { storeName: '', storeEmail: '', storePhone: '', address: '', currency: 'AUD', taxRate: 10, shippingCost: 0, freeShippingThreshold: 50, turnaroundDays: '3-5', footerText: '', termsUrl: '/terms-of-service', privacyUrl: '/privacy-policy', allowGuestCheckout: true, paymentTestMode: true }

export default function SettingsPage() {
  const { data: session, isPending } = useAdminSession()
  const [settings, setSettings] = useState<Settings>(initial)
  const [configuration, setConfiguration] = useState<Configuration | null>(null)
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [message, setMessage] = useState('')
  const [error, setError] = useState('')
  useEffect(() => { if (getUserRole(session?.user) !== 'admin') return; void (async () => { try { const response = await fetch('/api/admin/settings', { cache: 'no-store' }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error?.message || 'Settings could not be loaded.'); setSettings(payload.data.settings); setConfiguration(payload.data.configuration) } catch (err) { setError(err instanceof Error ? err.message : 'Settings could not be loaded.') } finally { setLoading(false) } })() }, [session?.user])
  function set<K extends keyof Settings>(key: K, value: Settings[K]) { setSettings((current) => ({ ...current, [key]: value })) }
  async function save(event: React.FormEvent) { event.preventDefault(); setSaving(true); setMessage(''); setError(''); try { const response = await fetch('/api/admin/settings', { method: 'PUT', headers: { 'content-type': 'application/json' }, body: JSON.stringify(settings) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error?.message || 'Settings could not be saved.'); setSettings(payload.data.settings); setConfiguration(payload.data.configuration); setMessage(payload.data.changedFields.length ? 'Settings saved successfully.' : 'No settings changed.') } catch (err) { setError(err instanceof Error ? err.message : 'Settings could not be saved.') } finally { setSaving(false) } }
  if (isPending || loading) return <div className="grid min-h-screen place-items-center">Loading settings…</div>
  if (!session?.user || getUserRole(session.user) !== 'admin') return <div className="grid min-h-screen place-items-center"><Link href={adminPath('/login')}>Admin sign in required</Link></div>
  const status = (label: string, ok: boolean, detail: string) => <div className="flex items-start gap-3 rounded-lg border p-3">{ok ? <CheckCircle2 className="mt-0.5 h-5 w-5 text-green-600" /> : <XCircle className="mt-0.5 h-5 w-5 text-amber-600" />}<div><p className="font-semibold">{label}</p><p className="text-xs text-muted-foreground">{detail}</p></div></div>
  return <main className="min-h-screen bg-background px-4 py-8"><form onSubmit={save} className="mx-auto max-w-7xl"><div className="flex items-center justify-between"><div><Link href={adminPath()} className="inline-flex items-center gap-2 text-sm font-semibold"><ArrowLeft className="h-4 w-4" /> Dashboard</Link><h1 className="mt-2 text-3xl font-black">Store settings</h1></div><Button type="submit" disabled={saving}><Save /> {saving ? 'Saving…' : 'Save settings'}</Button></div>
    {error && <p role="alert" className="mt-5 rounded-md bg-red-50 p-3 text-red-700">{error}</p>}{message && <p role="status" className="mt-5 rounded-md bg-green-50 p-3 text-green-700">{message}</p>}
    <div className="mt-6 grid gap-6 xl:grid-cols-[1fr_350px]"><div className="space-y-6"><section className="rounded-xl border bg-card p-6"><h2 className="text-xl font-bold">Store and contact information</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Store name<Input required className="mt-2" value={settings.storeName} onChange={(e) => set('storeName', e.target.value)} /></label><label className="text-sm font-semibold">Contact email<Input required type="email" className="mt-2" value={settings.storeEmail} onChange={(e) => set('storeEmail', e.target.value)} /></label><label className="text-sm font-semibold">Phone<Input className="mt-2" value={settings.storePhone} onChange={(e) => set('storePhone', e.target.value)} /></label><label className="text-sm font-semibold">Currency (ISO)<Input required maxLength={3} className="mt-2 uppercase" value={settings.currency} onChange={(e) => set('currency', e.target.value.toUpperCase())} /></label><label className="text-sm font-semibold sm:col-span-2">Store address<textarea className="mt-2 min-h-24 w-full rounded-md border bg-background p-3" value={settings.address} onChange={(e) => set('address', e.target.value)} /></label></div></section>
      <section className="rounded-xl border bg-card p-6"><h2 className="text-xl font-bold">Checkout and fulfilment</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Tax rate (%)<Input required type="number" min="0" max="100" step="0.01" className="mt-2" value={settings.taxRate} onChange={(e) => set('taxRate', e.target.value)} /></label><label className="text-sm font-semibold">Shipping cost<Input required type="number" min="0" step="0.01" className="mt-2" value={settings.shippingCost} onChange={(e) => set('shippingCost', e.target.value)} /></label><label className="text-sm font-semibold">Free shipping threshold<Input required type="number" min="0" step="0.01" className="mt-2" value={settings.freeShippingThreshold} onChange={(e) => set('freeShippingThreshold', e.target.value)} /></label><label className="text-sm font-semibold">Turnaround time<Input required className="mt-2" value={settings.turnaroundDays} onChange={(e) => set('turnaroundDays', e.target.value)} /></label></div><div className="mt-5 flex flex-col gap-3"><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={settings.allowGuestCheckout} onChange={(e) => set('allowGuestCheckout', e.target.checked)} /> Allow guest checkout</label><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={settings.paymentTestMode} onChange={(e) => set('paymentTestMode', e.target.checked)} /> Payment test mode (required until live SDK adapters are enabled)</label></div></section>
      <section className="rounded-xl border bg-card p-6"><h2 className="text-xl font-bold">Footer and legal</h2><div className="mt-5 grid gap-4"><label className="text-sm font-semibold">Footer text<Input className="mt-2" value={settings.footerText} onChange={(e) => set('footerText', e.target.value)} /></label><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Terms URL<Input className="mt-2" value={settings.termsUrl} onChange={(e) => set('termsUrl', e.target.value)} /></label><label className="text-sm font-semibold">Privacy URL<Input className="mt-2" value={settings.privacyUrl} onChange={(e) => set('privacyUrl', e.target.value)} /></label></div></div></section>
      <section className="rounded-xl border bg-card p-6"><h2 className="text-xl font-bold">Integration status</h2><p className="mt-1 text-sm text-muted-foreground">Secret values are checked on the server and never returned to this page.</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{configuration && <>{status(configuration.storage.provider, configuration.storage.configured, configuration.storage.configured ? 'Credentials, bucket, and public URL are present.' : 'One or more required R2 variables are missing.')}{status('Stripe / card', settings.paymentTestMode || configuration.payments.stripeConfigured, settings.paymentTestMode ? 'Safe simulator enabled; no card data is collected.' : configuration.payments.stripeConfigured ? 'Environment credentials detected.' : 'Stripe environment variables are missing.')}{status('PayPal', settings.paymentTestMode || configuration.payments.paypalConfigured, settings.paymentTestMode ? 'Safe simulator enabled.' : configuration.payments.paypalConfigured ? 'Environment credentials detected.' : 'PayPal environment variables are missing.')}</>}</div></section>
      <div className="flex justify-end"><Button type="submit" size="lg" disabled={saving}><Save /> {saving ? 'Saving…' : 'Save settings'}</Button></div></div></div>
  </form></main>
}
