import { NextRequest, NextResponse } from 'next/server'
import { eq } from 'drizzle-orm'
import { db } from '@/lib/db/client'
import { userProfiles, users } from '@/lib/db/schema'
import { getSession } from '@/lib/auth/middleware'

const phonePattern = /^[+()\d\s.-]{7,30}$/
export async function GET() { const session = await getSession(); if (!session?.user) return NextResponse.json({ error: { message: 'Sign in is required.' } }, { status: 401 }); const [profile] = await db.select().from(userProfiles).where(eq(userProfiles.userId, session.user.id)).limit(1); return NextResponse.json({ data: { profile: { name: session.user.name, email: session.user.email, ...(profile || {}) } } }) }
export async function PUT(request: NextRequest) { const session = await getSession(); if (!session?.user) return NextResponse.json({ error: { message: 'Sign in is required.' } }, { status: 401 }); try { const body = await request.json() as Record<string, unknown>; const name = typeof body.name === 'string' ? body.name.trim().slice(0,255) : ''; const phone = typeof body.phone === 'string' ? body.phone.trim() : ''; const alternatePhone = typeof body.alternatePhone === 'string' ? body.alternatePhone.trim() : ''; const company=typeof body.company==='string'?body.company.trim().slice(0,255):''; if(name.length<2)throw new Error('Enter a valid full name.'); if(phone&&!phonePattern.test(phone)||alternatePhone&&!phonePattern.test(alternatePhone))throw new Error('Enter a valid phone number.'); const deliveryInstructions=typeof body.deliveryInstructions==='string'?body.deliveryInstructions.trim().slice(0,2000):''; const [profile] = await db.transaction(async(tx)=>{await tx.update(users).set({name,updatedAt:new Date()}).where(eq(users.id,session.user.id));return tx.insert(userProfiles).values({userId:session.user.id,company,phone,alternatePhone,deliveryInstructions}).onConflictDoUpdate({target:userProfiles.userId,set:{company,phone,alternatePhone,deliveryInstructions,updatedAt:new Date()}}).returning()}); return NextResponse.json({data:{profile:{name,email:session.user.email,...profile}}}) } catch(error){return NextResponse.json({error:{message:error instanceof Error?error.message:'Profile update failed.'}},{status:400})} }
