'use client'

import { useState } from 'react'
import { FileCheck2, FileUp, Trash2 } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'

export interface ArtworkSelection { id: string; filename: string; previewUrl: string | null }
export function ArtworkUploadCard({ productId, sizeId, quantity, value, onChange }: { productId: string; sizeId: string; quantity: number; value: ArtworkSelection | null; onChange: (value: ArtworkSelection | null) => void }) {
  const [notes, setNotes] = useState(''); const [orientation, setOrientation] = useState('unspecified'); const [progress, setProgress] = useState(0); const [error, setError] = useState(''); const [uploading, setUploading] = useState(false)
  function upload(file?: File) { if (!file || uploading) return; setUploading(true); setProgress(0); setError(''); const form = new FormData(); form.set('file', file); form.set('productId', productId); form.set('sizeId', sizeId); form.set('notes', notes); form.set('orientation', orientation); form.set('quantityReference', String(quantity)); const request = new XMLHttpRequest(); request.open('POST', '/api/artwork'); request.responseType = 'json'; request.upload.onprogress = (event) => { if (event.lengthComputable) setProgress(Math.round(event.loaded / event.total * 100)) }; request.onload = () => { setUploading(false); if (request.status >= 200 && request.status < 300) { const row = request.response.data.artwork; const previous = value; onChange({ id: row.id, filename: row.originalFilename, previewUrl: row.previewUrl }); if (previous) void fetch('/api/artwork', { method: 'DELETE', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ id: previous.id }) }) } else setError(request.response?.error?.message || 'Artwork upload failed.') }; request.onerror = () => { setUploading(false); setError('Artwork upload connection failed.') }; request.send(form) }
  async function remove() { if (!value) return; const response = await fetch('/api/artwork', { method: 'DELETE', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ id: value.id }) }); const payload = await response.json(); if (!response.ok) return setError(payload.error?.message || 'Artwork could not be removed.'); onChange(null) }
  return <section className="mt-5 rounded-xl border bg-card p-5"><div className="flex items-start gap-3"><FileUp className="mt-1 h-6 w-6 text-primary" /><div><h2 className="text-lg font-bold">Upload Your Artwork</h2><p className="text-sm text-muted-foreground">Upload a print-ready PDF, PNG, SVG, or EPS instead of using the online editor. Maximum 100 MB.</p></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold">Optional notes<textarea className="mt-1 min-h-20 w-full rounded border p-2" value={notes} onChange={(e) => setNotes(e.target.value)} /></label><label className="text-sm font-semibold">Preferred orientation<select className="mt-1 h-10 w-full rounded border px-2" value={orientation} onChange={(e) => setOrientation(e.target.value)}><option value="unspecified">No preference</option><option value="landscape">Landscape</option><option value="portrait">Portrait</option></select></label></div>{value ? <div className="mt-4 flex items-center justify-between rounded border border-green-200 bg-green-50 p-3"><div className="flex items-center gap-2"><FileCheck2 className="text-green-700" /><span className="text-sm font-semibold">{value.filename}</span></div><Button type="button" size="sm" variant="outline" className="text-red-600" onClick={() => void remove()}><Trash2 /> Remove</Button></div> : <label className={`mt-4 flex cursor-pointer items-center justify-center gap-2 rounded border border-dashed p-5 text-sm font-semibold ${!sizeId ? 'pointer-events-none opacity-50' : ''}`}><FileUp /> {uploading ? `Uploading ${progress}%` : 'Choose artwork file'}<Input className="sr-only" type="file" accept="application/pdf,image/png,image/svg+xml,.eps,application/postscript" disabled={!sizeId || uploading} onChange={(e) => { upload(e.target.files?.[0]); e.currentTarget.value = '' }} /></label>}{uploading && <div className="mt-2 h-2 rounded bg-secondary"><div className="h-full rounded bg-primary" style={{ width: `${progress}%` }} /></div>}{error && <p role="alert" className="mt-3 text-sm text-red-700">{error}</p>}</section>
}
