'use client'

import Link from 'next/link'
import { ArrowLeft, ShoppingCart, Trash2 } from 'lucide-react'
import { useCart } from '@/lib/cart-context'
import { Button } from '@/components/ui/button'

export default function CartPage() {
  const { items, total, ready, removeItem, updateQuantity } = useCart()
  if (!ready) return <div className="grid min-h-[60vh] place-items-center">Loading cart…</div>
  if (!items.length) return <div className="grid min-h-[70vh] place-items-center text-center"><div><ShoppingCart className="mx-auto h-16 w-16 text-muted-foreground" /><h1 className="mt-4 text-2xl font-bold">Your cart is empty</h1><p className="mt-2 text-muted-foreground">Choose a product and size to get started.</p><Link href="/products"><Button className="mt-6"><ArrowLeft /> Browse products</Button></Link></div></div>
  return <main className="min-h-screen bg-background px-4 py-10"><div className="mx-auto max-w-6xl"><h1 className="text-3xl font-black">Shopping cart</h1><p className="mt-2 text-muted-foreground">Your selections are saved on this device.</p><div className="mt-8 grid gap-8 lg:grid-cols-[1fr_340px]"><section className="overflow-hidden rounded-xl border bg-card"><ul className="divide-y">{items.map((item) => <li key={item.lineId} className="flex gap-4 p-5">{item.image && <img src={item.image} alt="" className="h-24 w-24 rounded object-cover" />}<div className="min-w-0 flex-1"><h2 className="font-bold">{item.productName}</h2><p className="text-sm text-muted-foreground">Size: {item.sizeLabel}</p>{item.templateName && <p className="text-sm text-muted-foreground">Template: {item.templateName}</p>}<p className="mt-2 text-sm font-semibold">${item.price.toFixed(2)} per unit</p><div className="mt-4 flex flex-wrap items-center gap-3"><div className="flex items-center rounded border"><button className="px-3 py-2" aria-label="Decrease quantity" onClick={() => updateQuantity(item.lineId, item.quantity - 1)}>−</button><span className="min-w-10 text-center">{item.quantity}</span><button className="px-3 py-2" aria-label="Increase quantity" onClick={() => updateQuantity(item.lineId, item.quantity + 1)}>+</button></div><Button variant="outline" size="sm" className="text-red-600" onClick={() => removeItem(item.lineId)}><Trash2 /> Remove</Button><span className="ml-auto font-bold">${(item.price * item.quantity).toFixed(2)}</span></div></div></li>)}</ul></section><aside className="h-fit rounded-xl border bg-card p-6 lg:sticky lg:top-6"><h2 className="text-xl font-bold">Order summary</h2><div className="mt-5 flex justify-between"><span>Subtotal</span><span className="font-bold">${total.toFixed(2)}</span></div><p className="mt-3 text-xs text-muted-foreground">Shipping and tax are calculated from saved store settings and revalidated on the server.</p><Link href="/checkout"><Button size="lg" className="mt-6 w-full">Proceed to checkout</Button></Link><Link href="/products"><Button size="lg" variant="outline" className="mt-3 w-full">Continue shopping</Button></Link></aside></div></div></main>
}
