import { NextRequest, NextResponse } from 'next/server'
import { and, eq } from 'drizzle-orm'
import { db } from '@/lib/db/client'
import { customerAddresses } from '@/lib/db/schema'
import { getSession } from '@/lib/auth/middleware'
import { validateAustralianLocation } from '@/lib/address/australia'
function clean(body:Record<string,unknown>){const text=(key:string,max=255)=>typeof body[key]==='string'?(body[key] as string).trim().slice(0,max):'';const phone=text('phone',30),alternatePhone=text('alternatePhone',30);if(!text('fullName')||!text('addressLine1',500))throw new Error('Complete all required address fields.');if(phone&&!/^[+()\d\s.-]{7,30}$/.test(phone)||alternatePhone&&!/^[+()\d\s.-]{7,30}$/.test(alternatePhone))throw new Error('Enter a valid phone number.');const location=validateAustralianLocation({suburb:body.suburb??body.city,state:body.state??body.region,postalCode:body.postalCode,country:body.country});return{label:text('label',80)||'Address',fullName:text('fullName'),phone,alternatePhone,addressLine1:text('addressLine1',500),addressLine2:text('addressLine2',500),city:location.suburb,region:location.state,postalCode:location.postalCode,country:location.country,deliveryInstructions:text('deliveryInstructions',2000),defaultShipping:body.defaultShipping===true,defaultBilling:body.defaultBilling===true,updatedAt:new Date()}}
export async function PUT(request:NextRequest,{params}:{params:Promise<{id:string}>}){const session=await getSession();if(!session?.user)return NextResponse.json({error:{message:'Sign in is required.'}},{status:401});try{const{id}=await params,input=clean(await request.json());const[address]=await db.transaction(async(tx)=>{if(input.defaultShipping)await tx.update(customerAddresses).set({defaultShipping:false}).where(eq(customerAddresses.userId,session.user.id));if(input.defaultBilling)await tx.update(customerAddresses).set({defaultBilling:false}).where(eq(customerAddresses.userId,session.user.id));return tx.update(customerAddresses).set(input).where(and(eq(customerAddresses.id,id),eq(customerAddresses.userId,session.user.id))).returning()});return address?NextResponse.json({data:{address}}):NextResponse.json({error:{message:'Address not found.'}},{status:404})}catch(error){return NextResponse.json({error:{message:error instanceof Error?error.message:'Address update failed.'}},{status:400})}}
export async function DELETE(_:NextRequest,{params}:{params:Promise<{id:string}>}){const session=await getSession();if(!session?.user)return NextResponse.json({error:{message:'Sign in is required.'}},{status:401});const{id}=await params;await db.delete(customerAddresses).where(and(eq(customerAddresses.id,id),eq(customerAddresses.userId,session.user.id)));return NextResponse.json({data:{deleted:id}})}
