import { NextRequest, NextResponse } from 'next/server'
import { eq } from 'drizzle-orm'
import { revalidatePath } from 'next/cache'
import { db } from '@/lib/db/client'
import { homepagePromotions, storageAssets } from '@/lib/db/schema'
import { getAdminSession } from '@/lib/auth/require-admin'
import { canonicalStoredAssetUrl } from '@/lib/storage/r2-public-url'

function clean(body:Record<string,unknown>){const text=(key:string,max:number)=>typeof body[key]==='string'?body[key].trim().slice(0,max):'';const internalTitle=text('internalTitle',255),headline=text('headline',255),description=text('description',5000),imageAssetId=text('imageAssetId',50)||null,imageUrl=imageAssetId?null:canonicalStoredAssetUrl(text('imageUrl',1000)||null),ctaLabel=text('ctaLabel',120)||null,ctaUrl=text('ctaUrl',1000)||null;if(!internalTitle||!headline||!description||!imageAssetId&&!imageUrl)throw new Error('Title, headline, description, and image are required.');return{internalTitle,headline,description,imageAssetId,imageUrl,ctaLabel,ctaUrl,alignment:body.alignment==='image_right'?'image_right':'image_left',enabled:body.enabled!==false,displayOrder:Number.isFinite(Number(body.displayOrder))?Math.round(Number(body.displayOrder)):0,productId:typeof body.productId==='string'&&body.productId?body.productId:null,categoryId:typeof body.categoryId==='string'&&body.categoryId?body.categoryId:null,updatedAt:new Date()}}
async function ensureAsset(id:string|null){if(!id)return;const[asset]=await db.select().from(storageAssets).where(eq(storageAssets.id,id)).limit(1);if(!asset||!['image/png','image/jpeg','image/webp'].includes(asset.contentType)||asset.status!=='available')throw new Error('Select an available PNG, JPG, or WebP image asset.')}
export async function PUT(request:NextRequest,{params}:{params:Promise<{id:string}>}){if(!(await getAdminSession()))return NextResponse.json({error:{message:'Admin access is required.'}},{status:401});try{const{id}=await params;const input=clean(await request.json());await ensureAsset(input.imageAssetId);const[row]=await db.update(homepagePromotions).set(input).where(eq(homepagePromotions.id,id)).returning();if(!row)return NextResponse.json({error:{message:'Promotion not found.'}},{status:404});revalidatePath('/');return NextResponse.json({data:{promotion:row}})}catch(error){return NextResponse.json({error:{message:error instanceof Error?error.message:'Promotion could not be updated.'}},{status:400})}}
export async function DELETE(_:NextRequest,{params}:{params:Promise<{id:string}>}){if(!(await getAdminSession()))return NextResponse.json({error:{message:'Admin access is required.'}},{status:401});const{id}=await params;await db.delete(homepagePromotions).where(eq(homepagePromotions.id,id));revalidatePath('/');return NextResponse.json({data:{deleted:id}})}
