'use client'

import { useCallback, useEffect, useState } from 'react'
import Link from 'next/link'
import { Activity, ChevronDown, ChevronUp, RefreshCw } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { adminPath } from '@/lib/auth/admin-path'

interface ActivityItem { id: string; adminName: string; actionType: string; entityType: string; entityId: string | null; entityName: string | null; description: string; createdAt: string }
const types = ['', 'product', 'template', 'hero_slide', 'product_category', 'order', 'payment', 'customer', 'settings', 'review']
function hrefFor(item: ActivityItem) { if (!item.entityId) return null; if (item.entityType === 'product') return adminPath(`/products/${item.entityId}`); if (item.entityType === 'order') return adminPath(`/orders/${item.entityId}`); if (item.entityType === 'template') return adminPath('/templates'); if (item.entityType === 'hero_slide') return adminPath('/homepage'); if (item.entityType === 'product_category') return adminPath('/products'); return null }

export function AdminActivityPanel() {
  const [items, setItems] = useState<ActivityItem[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [expanded, setExpanded] = useState(() => typeof window === 'undefined' || localStorage.getItem('admin-activity-expanded') !== 'false'); const [filters, setFilters] = useState({ type: '', admin: '', from: '' }); const [offset, setOffset] = useState(0); const [hasMore, setHasMore] = useState(false)
  const load = useCallback(async (append = false) => { setLoading(true); setError(''); try { const nextOffset = append ? offset : 0; const params = new URLSearchParams({ limit: '15', offset: String(nextOffset) }); if (filters.type) params.set('type', filters.type); if (filters.admin) params.set('admin', filters.admin); if (filters.from) params.set('from', filters.from); const response = await fetch(`/api/admin/activity?${params}`, { cache: 'no-store' }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error?.message || 'Activity could not be loaded.'); setItems((current) => append ? [...current, ...payload.data.activity] : payload.data.activity); setHasMore(payload.data.hasMore); setOffset(nextOffset + payload.data.activity.length) } catch (err) { setError(err instanceof Error ? err.message : 'Activity could not be loaded.') } finally { setLoading(false) } }, [filters, offset])
  useEffect(() => { const timer = window.setTimeout(() => void load(false), 0); return () => window.clearTimeout(timer) }, [filters]) // eslint-disable-line react-hooks/exhaustive-deps
  function toggle() { setExpanded((value) => { localStorage.setItem('admin-activity-expanded', String(!value)); return !value }) }
  return <aside className="rounded-xl border border-border bg-card p-5" aria-label="Recent admin activity"><div className="flex items-center justify-between"><h2 className="flex items-center gap-2 font-bold"><Activity className="h-5 w-5 text-primary" /> Recent activity</h2><div className="flex gap-1"><button onClick={() => void load(false)} aria-label="Refresh activity" className="rounded p-1 hover:bg-secondary"><RefreshCw className={`h-4 w-4 ${loading ? 'animate-spin' : ''}`} /></button><button onClick={toggle} aria-label={expanded ? 'Collapse activity' : 'Expand activity'} className="rounded p-1 hover:bg-secondary">{expanded ? <ChevronUp /> : <ChevronDown />}</button></div></div>{expanded && <><div className="mt-4 grid gap-2 sm:grid-cols-3"><select aria-label="Activity type" className="h-10 rounded border bg-background px-2 text-sm" value={filters.type} onChange={(e) => setFilters({ ...filters, type: e.target.value })}>{types.map((type) => <option key={type} value={type}>{type ? type.replaceAll('_', ' ') : 'All activity types'}</option>)}</select><Input aria-label="Administrator filter" placeholder="Administrator" value={filters.admin} onChange={(e) => setFilters({ ...filters, admin: e.target.value })} /><Input aria-label="Activity date" type="date" value={filters.from} onChange={(e) => setFilters({ ...filters, from: e.target.value })} /></div>{error && <p className="mt-4 rounded-md bg-red-50 p-3 text-sm text-red-700">{error}</p>}{!loading && !error && !items.length && <p className="mt-4 text-sm text-muted-foreground">No activity matches these filters.</p>}<ol className="mt-4 space-y-4">{items.map((item) => { const href = hrefFor(item); return <li key={item.id} className="border-l-2 border-primary/30 pl-3 text-sm"><p className="font-semibold">{href ? <Link className="hover:text-primary" href={href}>{item.entityName || item.actionType}</Link> : item.entityName || item.actionType}</p><p className="text-muted-foreground">{item.description}</p><p className="mt-1 text-xs text-muted-foreground">{item.adminName} · {new Date(item.createdAt).toLocaleString()}</p></li> })}</ol>{hasMore && <Button className="mt-4" variant="outline" onClick={() => void load(true)} disabled={loading}>Load more</Button>}</>}</aside>
}
