'use client'

import { useCallback, useEffect, useState } from 'react'
import { Edit2, Plus, Save, Trash2, X } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { uploadAdminFile } from '@/lib/storage/upload-client'
import { ImageCropUpload } from '@/components/admin/image-crop-upload'

interface Category { id: string; name: string; description: string | null; imageAssetId: string | null; imageUrl: string | null; enabled: boolean; showOnHomepage: boolean; displayOrder: number }
const blank = { name: '', description: '', imageAssetId: '', imageUrl: '', enabled: true, showOnHomepage: false, displayOrder: 0 }

export function CategoryManager() {
  const [rows, setRows] = useState<Category[]>([]); const [editing, setEditing] = useState<string | null>(null); const [form, setForm] = useState(blank); const [message, setMessage] = useState(''); const [saving, setSaving] = useState(false)
  const load = useCallback(async () => { const response = await fetch('/api/admin/categories', { cache: 'no-store' }); const payload = await response.json(); if (response.ok) setRows(payload.data.categories); else setMessage(payload.error?.message || 'Categories could not be loaded.') }, [])
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer) }, [load])
  function edit(row?: Category) { setEditing(row?.id || null); setForm(row ? { name: row.name, description: row.description || '', imageAssetId: row.imageAssetId || '', imageUrl: row.imageUrl || '', enabled: row.enabled, showOnHomepage: row.showOnHomepage, displayOrder: row.displayOrder } : blank); setMessage('') }
  async function upload(file?: File) { if (!file) return; try { const asset = await uploadAdminFile(file, 'homepage', 'homepage/categories'); setForm((current) => ({ ...current, imageAssetId: asset.id, imageUrl: asset.url })); setMessage('Category image uploaded.') } catch (error) { setMessage(error instanceof Error ? error.message : 'Image upload failed.') } }
  async function save(event: React.FormEvent) { event.preventDefault(); if (saving) return; setSaving(true); try { const response = await fetch(editing ? `/api/admin/categories/${editing}` : '/api/admin/categories', { method: editing ? 'PUT' : 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(form) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error?.message || 'Category could not be saved.'); setMessage(editing ? 'Category updated.' : 'Category created.'); edit(); await load() } catch (error) { setMessage(error instanceof Error ? error.message : 'Category could not be saved.') } finally { setSaving(false) } }
  async function remove(row: Category) { if (!window.confirm(`Delete “${row.name}”?`)) return; const response = await fetch(`/api/admin/categories/${row.id}`, { method: 'DELETE' }); const payload = await response.json(); setMessage(response.ok ? 'Category deleted.' : payload.error?.message || 'Category could not be deleted.'); if (response.ok) await load() }
  return <section className="rounded-xl border bg-card p-6"><div className="flex items-center justify-between"><div><h2 className="text-xl font-bold">Categories and homepage cards</h2><p className="text-sm text-muted-foreground">Manage category content, order, visibility, and images.</p></div><Button type="button" variant="outline" onClick={() => edit()}><Plus /> New category</Button></div>{message && <p className="mt-4 rounded bg-secondary p-3 text-sm">{message}</p>}
    <form onSubmit={save} className="mt-5 grid gap-3 rounded-lg border p-4 sm:grid-cols-2"><label className="text-sm font-semibold">Title<Input required className="mt-1" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label className="text-sm font-semibold">Display order<Input type="number" min="0" className="mt-1" value={form.displayOrder} onChange={(e) => setForm({ ...form, displayOrder: Math.max(0, Number(e.target.value) || 0) })} /></label><label className="text-sm font-semibold sm:col-span-2">Description<textarea className="mt-1 min-h-20 w-full rounded border p-2" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label><div className="sm:col-span-2"><ImageCropUpload label="Category image" recommendedWidth={1200} recommendedHeight={900} value={form.imageUrl || undefined} onCropped={(file) => upload(file)} /></div><div className="space-y-2"><label className="flex gap-2 text-sm"><input type="checkbox" checked={form.enabled} onChange={(e) => setForm({ ...form, enabled: e.target.checked })} /> Enabled</label><label className="flex gap-2 text-sm"><input type="checkbox" checked={form.showOnHomepage} onChange={(e) => setForm({ ...form, showOnHomepage: e.target.checked })} /> Show on homepage</label></div><div className="flex gap-2 sm:col-span-2"><Button type="submit" disabled={saving}><Save /> {saving ? 'Saving...' : editing ? 'Update' : 'Create'}</Button>{editing && <Button type="button" variant="outline" onClick={() => edit()}><X /> Cancel</Button>}</div></form>
    <div className="mt-5 grid gap-3 md:grid-cols-2">{rows.map((row) => <article key={row.id} className="flex gap-3 rounded border p-3">{row.imageUrl ? <img src={row.imageUrl} alt="" className="h-20 w-24 rounded object-cover" /> : <div className="h-20 w-24 rounded bg-secondary" />}<div className="min-w-0 flex-1"><p className="font-semibold">{row.name}</p><p className="text-xs text-muted-foreground">{row.enabled ? 'Enabled' : 'Disabled'} · {row.showOnHomepage ? 'Homepage' : 'Hidden from homepage'} · #{row.displayOrder}</p><div className="mt-2 flex gap-2"><Button size="sm" variant="outline" onClick={() => edit(row)}><Edit2 /> Edit</Button><Button size="sm" variant="outline" className="text-red-600" onClick={() => void remove(row)}><Trash2 /></Button></div></div></article>)}</div>
  </section>
}
