import { NextRequest, NextResponse } from 'next/server'
import { eq } from 'drizzle-orm'
import { revalidatePath } from 'next/cache'
import { db } from '@/lib/db/client'
import { homepagePromotions, storageAssets } from '@/lib/db/schema'
import { getAdminSession } from '@/lib/auth/require-admin'
import { getHomepagePromotions } from '@/lib/home/promotion-data'

function clean(body:Record<string,unknown>){const text=(key:string,max:number)=>typeof body[key]==='string'?body[key].trim().slice(0,max):'';const internalTitle=text('internalTitle',255),headline=text('headline',255),description=text('description',5000),imageAssetId=text('imageAssetId',50)||null,imageUrl=text('imageUrl',1000)||null,ctaLabel=text('ctaLabel',120)||null,ctaUrl=text('ctaUrl',1000)||null,alignment=body.alignment==='image_right'?'image_right':'image_left';if(!internalTitle||!headline||!description)throw new Error('Internal title, public headline, and description are required.');if(!imageAssetId&&!imageUrl)throw new Error('A promotional image is required.');if(ctaUrl&&!/^\/(?!\/)|^https?:\/\//i.test(ctaUrl))throw new Error('CTA URL must be a local path or web address.');return{internalTitle,headline,description,imageAssetId,imageUrl,ctaLabel,ctaUrl,alignment,enabled:body.enabled!==false,displayOrder:Number.isFinite(Number(body.displayOrder))?Math.round(Number(body.displayOrder)):0,productId:typeof body.productId==='string'&&body.productId?body.productId:null,categoryId:typeof body.categoryId==='string'&&body.categoryId?body.categoryId:null}}
async function ensureAsset(id:string|null){if(!id)return;const[asset]=await db.select().from(storageAssets).where(eq(storageAssets.id,id)).limit(1);if(!asset||!['image/png','image/jpeg','image/webp'].includes(asset.contentType)||asset.status!=='available')throw new Error('Select an available PNG, JPG, or WebP image asset.')}
export async function GET(){if(!(await getAdminSession()))return NextResponse.json({error:{message:'Admin access is required.'}},{status:401});return NextResponse.json({data:{promotions:await getHomepagePromotions(false)}})}
export async function POST(request:NextRequest){if(!(await getAdminSession()))return NextResponse.json({error:{message:'Admin access is required.'}},{status:401});try{const input=clean(await request.json());await ensureAsset(input.imageAssetId);const[row]=await db.insert(homepagePromotions).values(input).returning();revalidatePath('/');return NextResponse.json({data:{promotion:row}},{status:201})}catch(error){return NextResponse.json({error:{message:error instanceof Error?error.message:'Promotion could not be created.'}},{status:400})}}
