'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { ShieldCheck } from 'lucide-react'
import { StripePaymentForm } from '@/components/payment/stripe-payment-form'
import { Button } from '@/components/ui/button'
import { useCart } from '@/lib/cart-context'

type PaymentState = { orderId: string; orderNumber: string; checkoutToken: string; expiresAt?: string | null; totals?: { subtotal: string; discount: string; couponCode: string | null; tax: string; shipping: string; total: string; currency: string } }
export default function PaymentPage() {
  const { items } = useCart(); const [payment, setPayment] = useState<{ clientSecret: string; orderNumber: string } | null>(null); const [totals, setTotals] = useState<PaymentState['totals']>(); const [error, setError] = useState('')
  useEffect(() => { let cancelled = false; try { const stored = sessionStorage.getItem('abs-payment'); if (!stored) throw new Error('Your checkout session has expired. Please return to checkout.'); const state = JSON.parse(stored) as PaymentState; if (state.expiresAt && new Date(state.expiresAt) <= new Date()) throw new Error('Your coupon reservation has expired. Please return to checkout and apply it again.'); setTotals(state.totals); void fetch('/api/payments/intent', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ orderId: state.orderId, checkoutToken: state.checkoutToken }) }).then(async (response) => { const payload = await response.json(); if (!response.ok || !payload.data?.clientSecret) throw new Error(payload.error?.message || 'Unable to prepare secure payment.'); if (!cancelled) setPayment({ clientSecret: payload.data.clientSecret, orderNumber: state.orderNumber }) }).catch((reason) => !cancelled && setError(reason instanceof Error ? reason.message : 'Unable to prepare secure payment.')) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to prepare secure payment.') } return () => { cancelled = true } }, [])
  if (error) return <main className="grid min-h-[60vh] place-items-center p-6"><div className="max-w-md text-center"><h1 className="text-2xl font-bold">Payment unavailable</h1><p className="mt-3 text-muted-foreground">{error}</p><Link href="/checkout"><Button className="mt-6">Return to checkout</Button></Link></div></main>
  return <main className="min-h-screen bg-background px-4 py-10"><div className="mx-auto grid max-w-6xl gap-8 lg:grid-cols-[1fr_440px]"><section className="rounded-xl border bg-card p-6"><h1 className="text-3xl font-black">Review your order</h1><p className="mt-2 text-muted-foreground">Your order total was validated on the server before payment.</p><div className="mt-6 space-y-4">{items.map((item) => <div key={item.lineId} className="flex gap-3 border-b pb-4">{item.image && <img src={item.image} alt="" className="h-20 w-20 rounded object-cover"/>}<div className="flex-1"><p className="font-semibold">{item.productName}</p><p className="text-sm text-muted-foreground">{item.sizeLabel} · Quantity {item.quantity}</p></div></div>)}</div>{totals && <div className="mt-5 space-y-2 border-t pt-4 text-sm"><div className="flex justify-between"><span>Subtotal</span><span>${Number(totals.subtotal).toFixed(2)}</span></div>{Number(totals.discount) > 0 && <div className="flex justify-between text-green-700"><span>Discount{totals.couponCode ? ` · ${totals.couponCode}` : ''}</span><span>−${Number(totals.discount).toFixed(2)}</span></div>}<div className="flex justify-between"><span>Shipping</span><span>${Number(totals.shipping).toFixed(2)}</span></div><div className="flex justify-between"><span>Tax</span><span>${Number(totals.tax).toFixed(2)}</span></div><div className="flex justify-between text-lg font-bold"><span>Total</span><span>{totals.currency} ${Number(totals.total).toFixed(2)}</span></div></div>}</section><section className="h-fit rounded-xl border bg-card p-6"><div className="flex gap-2"><ShieldCheck className="text-primary"/><div><h2 className="text-xl font-bold">Secure payment</h2><p className="text-sm text-muted-foreground">Powered by Stripe</p></div></div>{payment ? <div className="mt-6"><StripePaymentForm {...payment}/></div> : <div className="mt-8 space-y-3"><div className="h-10 animate-pulse rounded bg-secondary"/><div className="h-10 animate-pulse rounded bg-secondary"/><p className="text-sm text-muted-foreground">Preparing Stripe Payment Element…</p></div>}</section></div></main>
}
