'use client'
import { useEffect, useState } from 'react'
import Link from 'next/link'
import { ArrowLeft, Mail } from 'lucide-react'
import { adminPath } from '@/lib/auth/admin-path'
import { Button } from '@/components/ui/button'

interface Enquiry { id:string;name:string;email:string;phone:string|null;company:string|null;orderNumber:string|null;enquiryType:string|null;subject:string;message:string;status:string;emailStatus:string;createdAt:string }
export default function EnquiriesPage(){const[rows,setRows]=useState<Enquiry[]>([]);const[error,setError]=useState('');async function load(){const response=await fetch('/api/admin/enquiries',{cache:'no-store'});const payload=await response.json();if(!response.ok)throw new Error(payload.error?.message||'Enquiries could not be loaded.');setRows(payload.data.enquiries)}useEffect(()=>{const timer=window.setTimeout(()=>void load().catch((caught)=>setError(caught instanceof Error?caught.message:'Enquiries could not be loaded.')),0);return()=>window.clearTimeout(timer)},[]);async function update(id:string,status:string){const response=await fetch(`/api/admin/enquiries/${id}`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({status})});const payload=await response.json();if(!response.ok){setError(payload.error?.message||'Status update failed.');return}await load()}return <main className="min-h-screen bg-background px-4 py-8"><div className="mx-auto max-w-6xl"><Link href={adminPath()} className="inline-flex items-center gap-2"><ArrowLeft/> Dashboard</Link><div className="mt-2 flex items-center gap-3"><Mail className="text-primary"/><h1 className="text-3xl font-black">Contact enquiries</h1></div>{error&&<p className="mt-4 rounded bg-red-50 p-3 text-red-700">{error}</p>}<div className="mt-6 space-y-4">{rows.length===0?<p className="rounded-xl border bg-card p-10 text-center text-muted-foreground">No enquiries yet.</p>:rows.map((row)=><article key={row.id} className="rounded-xl border bg-card p-5"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-bold">{row.subject}</h2><p className="text-sm text-muted-foreground">{row.name} · <a className="text-primary" href={`mailto:${row.email}`}>{row.email}</a>{row.phone&&` · ${row.phone}`}</p><p className="mt-1 text-xs text-muted-foreground">{row.enquiryType||'General'}{row.company&&` · ${row.company}`}{row.orderNumber&&` · Order ${row.orderNumber}`} · Email {row.emailStatus}</p></div><time className="text-xs text-muted-foreground">{new Date(row.createdAt).toLocaleString()}</time></div><p className="mt-4 whitespace-pre-wrap rounded bg-secondary p-3 text-sm">{row.message}</p><div className="mt-4 flex gap-2">{['new','read','resolved'].map((status)=><Button key={status} type="button" size="sm" variant={row.status===status?'default':'outline'} onClick={()=>void update(row.id,status)}>{status}</Button>)}</div></article>)}</div></div></main>}
