import type { Metadata } from 'next'
import { ContentPage } from '@/components/content/content-page'
import { ContactForm } from '@/components/content/contact-form'
import { SocialIcon } from '@/components/shared/social-icon'
import { loadStoreSettings } from '@/lib/store/load-settings'
import { DEFAULT_STORE_SETTINGS } from '@/lib/store/settings'

export const metadata:Metadata={title:'Contact | Ali Baba Signs',description:'Contact Ali Baba Signs about custom signage, artwork, existing orders, or trade enquiries.'}

export default async function ContactPage(){
  const settings = await loadStoreSettings().catch(() => DEFAULT_STORE_SETTINGS)
  const locations = settings.locations.filter((location)=>location.enabled).sort((a,b)=>a.displayOrder-b.displayOrder)
  const socials = settings.socialLinks.filter((link)=>link.enabled).sort((a,b)=>a.displayOrder-b.displayOrder)
  return <ContentPage eyebrow="Contact" title="Tell us about your signage project" intro="Send the details below and our team will have the context needed to help."><div className="grid gap-8 md:grid-cols-[1fr_2fr]"><aside className="space-y-5"><div><h2 className="font-bold">Email</h2><a className="text-primary" href={`mailto:${settings.storeEmail}`}>{settings.storeEmail}</a>{settings.secondaryEmail&&<a className="mt-1 block text-primary" href={`mailto:${settings.secondaryEmail}`}>{settings.secondaryEmail}</a>}</div>{settings.storePhone&&<div><h2 className="font-bold">Phone</h2><a className="text-primary" href={`tel:${settings.storePhone.replace(/[^+\d]/g,'')}`}>{settings.storePhone}</a>{settings.secondaryPhone&&<a className="mt-1 block text-primary" href={`tel:${settings.secondaryPhone.replace(/[^+\d]/g,'')}`}>{settings.secondaryPhone}</a>}</div>}{settings.address&&<div><h2 className="font-bold">Location</h2><p className="text-sm text-muted-foreground">{settings.address}</p></div>}{settings.businessHours&&<div><h2 className="font-bold">Business hours</h2><p className="whitespace-pre-line text-sm text-muted-foreground">{settings.businessHours}</p></div>}{locations.map((location)=><div key={location.id} className="rounded-lg border p-3"><h2 className="font-bold">{location.name}</h2><p className="mt-1 whitespace-pre-line text-sm text-muted-foreground">{location.address}</p>{location.phone&&<a className="mt-1 block text-sm text-primary" href={`tel:${location.phone.replace(/[^+\d]/g,'')}`}>{location.phone}</a>}{location.email&&<a className="block text-sm text-primary" href={`mailto:${location.email}`}>{location.email}</a>}{location.businessHours&&<p className="mt-2 whitespace-pre-line text-xs text-muted-foreground">{location.businessHours}</p>}{location.mapUrl&&<a className="mt-2 inline-block text-sm font-semibold text-primary" href={location.mapUrl} target="_blank" rel="noopener noreferrer">Open map</a>}</div>)}{socials.length>0&&<div><h2 className="font-bold">Follow or message us</h2><div className="mt-2 flex flex-wrap gap-2">{socials.map((link)=><a key={link.id} href={link.url} target="_blank" rel="noopener noreferrer" aria-label={link.platform} className="grid h-10 w-10 place-items-center rounded-full border text-primary hover:bg-primary hover:text-white"><SocialIcon platform={link.platform}/></a>)}</div></div>}<div><h2 className="font-bold">Helpful details</h2><p className="text-sm text-muted-foreground">Include the product type, finished size, quantity, deadline, delivery location, and whether artwork is ready.</p></div></aside><ContactForm/></div></ContentPage>
}
