'use client'

import { FormEvent, useCallback, useEffect, useState } from 'react'
import Link from 'next/link'
import { adminPath } from '@/lib/auth/admin-path'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { ImageCropUpload } from '@/components/admin/image-crop-upload'
import { uploadAdminFile } from '@/lib/storage/upload-client'

type Coupon = { id: string; code: string; description: string | null; discountType: 'percent' | 'fixed'; discountValue: string; active: boolean; startsAt: string | null; endsAt: string | null; usageLimit: number | null; usedCount: number; perCustomerUsageLimit: number | null; minimumSubtotal: string | null; maxDiscountAmount: string | null; visibility: 'private' | 'public' | 'customer_specific'; productIds: string[]; categoryIds: string[]; customerIds: string[] }
type Offer = { id: string; title: string; slug: string; couponId: string | null; shortDescription: string | null; fullDescription: string | null; terms: string | null; imageAssetId: string | null; imageUrl: string | null; mobileImageAssetId: string | null; mobileImageUrl: string | null; badgeText: string | null; ctaLabel: string | null; ctaUrl: string | null; showOnHomepage: boolean; showInOffersPage: boolean; showInProfile: boolean; featured: boolean; enabled: boolean; startsAt: string | null; endsAt: string | null; displayOrder: number }
type Option = { id: string; name: string }
type Customer = Option & { email: string }
type Media = { id: string; filename: string; source: string; url: string }

const blankCoupon = () => ({ code: '', description: '', discountType: 'percent', discountValue: '', active: true, startsAt: '', endsAt: '', usageLimit: '', perCustomerUsageLimit: '', minimumSubtotal: '', maxDiscountAmount: '', visibility: 'private', productIds: [] as string[], categoryIds: [] as string[], customerIds: [] as string[] })
const blankOffer = () => ({ title: '', slug: '', couponId: '', shortDescription: '', fullDescription: '', terms: '', imageAssetId: '', imageUrl: '', mobileImageAssetId: '', mobileImageUrl: '', badgeText: '', ctaLabel: 'Shop now', ctaUrl: '/products', showOnHomepage: false, showInOffersPage: true, showInProfile: true, featured: false, enabled: true, startsAt: '', endsAt: '', displayOrder: '0' })
const dateValue = (value: string | null) => value ? new Date(value).toISOString().slice(0, 16) : ''

function Checks({ label, options, selected, onChange, customer }: { label: string; options: Option[]; selected: string[]; onChange: (next: string[]) => void; customer?: boolean }) {
  return <fieldset className="rounded border p-3"><legend className="px-1 text-sm font-semibold">{label}</legend><div className="mt-1 max-h-32 space-y-1 overflow-auto text-sm">{options.length ? options.map((item) => <label key={item.id} className="flex gap-2"><input type="checkbox" checked={selected.includes(item.id)} onChange={(event) => onChange(event.target.checked ? [...selected, item.id] : selected.filter((id) => id !== item.id))}/><span>{item.name}{customer ? ` (${(item as Customer).email})` : ''}</span></label>) : <p className="text-muted-foreground">No options available.</p>}</div></fieldset>
}

export default function CouponsClient() {
  const [coupons, setCoupons] = useState<Coupon[]>([]), [offers, setOffers] = useState<Offer[]>([])
  const [products, setProducts] = useState<Option[]>([]), [categories, setCategories] = useState<Option[]>([]), [customers, setCustomers] = useState<Customer[]>([]), [media, setMedia] = useState<Media[]>([])
  const [couponForm, setCouponForm] = useState(blankCoupon), [offerForm, setOfferForm] = useState(blankOffer)
  const [editingCoupon, setEditingCoupon] = useState<string | null>(null), [editingOffer, setEditingOffer] = useState<string | null>(null)
  const [message, setMessage] = useState(''), [busy, setBusy] = useState(false)

  const load = useCallback(async () => {
    const [couponResponse, offerResponse] = await Promise.all([fetch('/api/admin/coupons'), fetch('/api/admin/offers')])
    const [couponPayload, offerPayload] = await Promise.all([couponResponse.json(), offerResponse.json()])
    if (!couponResponse.ok) throw new Error(couponPayload.error?.message || 'Could not load coupons.')
    if (!offerResponse.ok) throw new Error(offerPayload.error?.message || 'Could not load offers.')
    setCoupons(couponPayload.data.coupons || []); setProducts(couponPayload.data.products || []); setCategories(couponPayload.data.categories || []); setCustomers(couponPayload.data.customers || [])
    setOffers(offerPayload.data.offers || []); setMedia(offerPayload.data.media || [])
  }, [])
  useEffect(() => { const timer = window.setTimeout(() => void load().catch((error) => setMessage(error.message)), 0); return () => window.clearTimeout(timer) }, [load])
  const setCoupon = (key: string, value: unknown) => setCouponForm((current) => ({ ...current, [key]: value }))
  const setOffer = (key: string, value: unknown) => setOfferForm((current) => ({ ...current, [key]: value }))

  async function saveCoupon(event: FormEvent) { event.preventDefault(); setBusy(true); setMessage(''); try { const response = await fetch(editingCoupon ? `/api/admin/coupons/${editingCoupon}` : '/api/admin/coupons', { method: editingCoupon ? 'PATCH' : 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(couponForm) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error?.message || 'Coupon could not be saved.'); setCouponForm(blankCoupon()); setEditingCoupon(null); setMessage('Coupon saved.'); await load() } catch (error) { setMessage(error instanceof Error ? error.message : 'Coupon could not be saved.') } finally { setBusy(false) } }
  async function saveOffer(event: FormEvent) { event.preventDefault(); setBusy(true); setMessage(''); try { const response = await fetch(editingOffer ? `/api/admin/offers/${editingOffer}` : '/api/admin/offers', { method: editingOffer ? 'PATCH' : 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(offerForm) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error?.message || 'Offer could not be saved.'); setOfferForm(blankOffer()); setEditingOffer(null); setMessage('Offer saved.'); await load() } catch (error) { setMessage(error instanceof Error ? error.message : 'Offer could not be saved.') } finally { setBusy(false) } }
  async function uploadOfferImage(file: File, previewUrl: string) { setBusy(true); setMessage('Uploading offer image…'); try { const asset = await uploadAdminFile(file, 'offer-image', 'hero'); setOfferForm((current) => ({ ...current, imageAssetId: asset.id, imageUrl: asset.url || previewUrl })); setMedia((current) => [{ id: asset.id, filename: asset.filename, source: 'Offer', url: asset.url }, ...current]); setMessage('Offer image uploaded. Save the offer when the preview looks right.') } catch (error) { setMessage(error instanceof Error ? error.message : 'Offer image upload failed.') } finally { setBusy(false) } }
  function selectMedia(id: string) { const selected = media.find((item) => item.id === id); setOfferForm((current) => ({ ...current, imageAssetId: selected?.id || '', imageUrl: selected?.url || '' })) }
  function editCoupon(coupon: Coupon) { setEditingCoupon(coupon.id); setCouponForm({ ...coupon, description: coupon.description || '', startsAt: dateValue(coupon.startsAt), endsAt: dateValue(coupon.endsAt), usageLimit: coupon.usageLimit?.toString() || '', perCustomerUsageLimit: coupon.perCustomerUsageLimit?.toString() || '', minimumSubtotal: coupon.minimumSubtotal || '', maxDiscountAmount: coupon.maxDiscountAmount || '' }); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  function editOffer(offer: Offer) { setEditingOffer(offer.id); setOfferForm({ ...offer, couponId: offer.couponId || '', shortDescription: offer.shortDescription || '', fullDescription: offer.fullDescription || '', terms: offer.terms || '', imageAssetId: offer.imageAssetId || '', imageUrl: offer.imageUrl || '', mobileImageAssetId: offer.mobileImageAssetId || '', mobileImageUrl: offer.mobileImageUrl || '', badgeText: offer.badgeText || '', ctaLabel: offer.ctaLabel || '', ctaUrl: offer.ctaUrl || '', startsAt: dateValue(offer.startsAt), endsAt: dateValue(offer.endsAt), displayOrder: String(offer.displayOrder) }); window.scrollTo({ top: document.body.scrollHeight, behavior: 'smooth' }) }
  async function remove(kind: 'coupons' | 'offers', id: string) { if (!window.confirm(`Delete this ${kind === 'coupons' ? 'coupon' : 'offer'}?`)) return; const response = await fetch(`/api/admin/${kind}/${id}`, { method: 'DELETE' }); const payload = await response.json(); if (!response.ok) return setMessage(payload.error?.message || 'Could not delete item.'); setMessage(payload.data?.archived ? 'Item archived because it has transaction history.' : 'Item deleted.'); await load() }

  return <main className="min-h-screen bg-background p-6"><Link href={adminPath()} className="text-sm font-semibold">← Dashboard</Link><h1 className="mt-2 text-3xl font-black">Offers &amp; Coupons</h1><p className="mt-1 text-muted-foreground">Manage discounts and the campaigns that promote them.</p>{message && <p role="status" className="mt-4 rounded border p-3 text-sm">{message}</p>}
    <section className="mt-6 rounded-xl border bg-card p-5"><h2 className="text-xl font-bold">{editingCoupon ? 'Edit coupon' : 'New coupon'}</h2><form onSubmit={saveCoupon} className="mt-4 grid gap-4 md:grid-cols-2">
      <label className="text-sm font-semibold">Code<Input required value={couponForm.code} onChange={(event) => setCoupon('code', event.target.value.toUpperCase())} placeholder="WELCOME10" className="mt-1"/></label><label className="text-sm font-semibold">Description<Input value={couponForm.description} onChange={(event) => setCoupon('description', event.target.value)} className="mt-1"/></label>
      <label className="text-sm font-semibold">Discount type<select value={couponForm.discountType} onChange={(event) => setCoupon('discountType', event.target.value)} className="mt-1 w-full rounded border p-2"><option value="percent">Percentage</option><option value="fixed">Fixed amount</option></select></label><label className="text-sm font-semibold">Discount value<Input required type="number" min="0.01" max={couponForm.discountType === 'percent' ? 100 : undefined} step="0.01" value={couponForm.discountValue} onChange={(event) => setCoupon('discountValue', event.target.value)} className="mt-1"/></label>
      <label className="text-sm font-semibold">Starts at<Input type="datetime-local" value={couponForm.startsAt} onChange={(event) => setCoupon('startsAt', event.target.value)} className="mt-1"/></label><label className="text-sm font-semibold">Ends at<Input type="datetime-local" value={couponForm.endsAt} onChange={(event) => setCoupon('endsAt', event.target.value)} className="mt-1"/></label>
      <label className="text-sm font-semibold">Total uses<Input type="number" min="1" value={couponForm.usageLimit} onChange={(event) => setCoupon('usageLimit', event.target.value)} className="mt-1"/></label><label className="text-sm font-semibold">Per-customer uses<Input type="number" min="1" value={couponForm.perCustomerUsageLimit} onChange={(event) => setCoupon('perCustomerUsageLimit', event.target.value)} className="mt-1"/></label>
      <label className="text-sm font-semibold">Minimum subtotal<Input type="number" min="0" step="0.01" value={couponForm.minimumSubtotal} onChange={(event) => setCoupon('minimumSubtotal', event.target.value)} className="mt-1"/></label><label className="text-sm font-semibold">Maximum discount<Input type="number" min="0" step="0.01" value={couponForm.maxDiscountAmount} onChange={(event) => setCoupon('maxDiscountAmount', event.target.value)} className="mt-1"/></label>
      <label className="text-sm font-semibold">Visibility<select value={couponForm.visibility} onChange={(event) => setCoupon('visibility', event.target.value)} className="mt-1 w-full rounded border p-2"><option value="private">Private / manual</option><option value="public">Public</option><option value="customer_specific">Customer specific</option></select></label><label className="mt-6 flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={couponForm.active} onChange={(event) => setCoupon('active', event.target.checked)}/>Active and redeemable</label>
      <Checks label="Eligible products (clear for all)" options={products} selected={couponForm.productIds} onChange={(ids) => setCoupon('productIds', ids)}/><Checks label="Eligible categories (clear for all)" options={categories} selected={couponForm.categoryIds} onChange={(ids) => setCoupon('categoryIds', ids)}/>{couponForm.visibility === 'customer_specific' && <Checks label="Assigned customers" options={customers} selected={couponForm.customerIds} onChange={(ids) => setCoupon('customerIds', ids)} customer/>}
      <div className="flex gap-3 md:col-span-2"><Button type="submit" disabled={busy}>{busy ? 'Saving…' : editingCoupon ? 'Save coupon' : 'Create coupon'}</Button>{editingCoupon && <Button type="button" variant="outline" onClick={() => { setEditingCoupon(null); setCouponForm(blankCoupon()) }}>Cancel edit</Button>}</div>
    </form></section>
    <section className="mt-6 overflow-x-auto rounded-xl border bg-card"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-3">Code</th><th>Discount</th><th>Usage</th><th>Status</th><th/></tr></thead><tbody>{coupons.map((coupon) => <tr key={coupon.id} className="border-b"><td className="p-3"><b>{coupon.code}</b><p className="text-xs text-muted-foreground">{coupon.description}</p></td><td>{coupon.discountType === 'percent' ? `${coupon.discountValue}%` : `$${coupon.discountValue}`}</td><td>{coupon.usedCount}/{coupon.usageLimit ?? '∞'}</td><td>{coupon.active ? 'Active' : 'Inactive'}</td><td><Button size="sm" variant="outline" onClick={() => editCoupon(coupon)}>Edit</Button> <Button size="sm" variant="outline" onClick={() => void remove('coupons', coupon.id)}>Delete</Button></td></tr>)}</tbody></table></section>

    <section className="mt-10 rounded-xl border bg-card p-5"><h2 className="text-xl font-bold">{editingOffer ? 'Edit marketing offer' : 'New marketing offer'}</h2><form onSubmit={saveOffer} className="mt-4 grid gap-4 md:grid-cols-2">
      <label className="text-sm font-semibold">Offer title<Input required value={offerForm.title} onChange={(event) => setOffer('title', event.target.value)} className="mt-1"/></label><label className="text-sm font-semibold">URL slug<Input value={offerForm.slug} onChange={(event) => setOffer('slug', event.target.value)} placeholder="spring-banner-savings" className="mt-1"/></label>
      <label className="text-sm font-semibold">Linked coupon<select value={offerForm.couponId} onChange={(event) => setOffer('couponId', event.target.value)} className="mt-1 w-full rounded border p-2"><option value="">No voucher code</option>{coupons.map((coupon) => <option key={coupon.id} value={coupon.id}>{coupon.code}</option>)}</select></label><label className="text-sm font-semibold">Use existing media<select value={offerForm.imageAssetId} onChange={(event) => selectMedia(event.target.value)} className="mt-1 w-full rounded border p-2"><option value="">Choose an active hero, promotion, or product image</option>{media.map((item) => <option key={item.id} value={item.id}>{item.source} · {item.filename}</option>)}</select></label>
      <div className="md:col-span-2"><ImageCropUpload label="Offer hero image" recommendedWidth={1600} recommendedHeight={900} value={offerForm.imageUrl} disabled={busy} onCropped={uploadOfferImage}/></div>
      <label className="text-sm font-semibold md:col-span-2">Short description<Input value={offerForm.shortDescription} onChange={(event) => setOffer('shortDescription', event.target.value)} className="mt-1"/></label><label className="text-sm font-semibold md:col-span-2">Full description<textarea value={offerForm.fullDescription} onChange={(event) => setOffer('fullDescription', event.target.value)} className="mt-1 min-h-24 w-full rounded border p-2"/></label><label className="text-sm font-semibold md:col-span-2">Terms and conditions<textarea value={offerForm.terms} onChange={(event) => setOffer('terms', event.target.value)} className="mt-1 min-h-20 w-full rounded border p-2"/></label>
      <label className="text-sm font-semibold">CTA label<Input value={offerForm.ctaLabel} onChange={(event) => setOffer('ctaLabel', event.target.value)} className="mt-1"/></label><label className="text-sm font-semibold">CTA URL<Input value={offerForm.ctaUrl} onChange={(event) => setOffer('ctaUrl', event.target.value)} placeholder="/products or https://…" className="mt-1"/></label>
      {(offerForm.imageUrl || offerForm.ctaLabel) && <div className="relative overflow-hidden rounded-xl border bg-zinc-900 md:col-span-2" style={{ aspectRatio: '16 / 9' }}>{offerForm.imageUrl && <img src={offerForm.imageUrl} alt="Offer preview" className="absolute inset-0 h-full w-full object-cover"/>}<div className="absolute inset-0 bg-gradient-to-r from-black/80 to-black/20"/><div className="relative flex h-full max-w-lg flex-col justify-center p-6 text-white"><p className="text-2xl font-black">{offerForm.title || 'Offer preview'}</p><p className="mt-2">{offerForm.shortDescription}</p>{offerForm.ctaLabel && <span className="mt-4 w-fit rounded bg-primary px-4 py-2 text-sm font-bold">{offerForm.ctaLabel}</span>}</div></div>}
      <label className="text-sm font-semibold">Starts at<Input type="datetime-local" value={offerForm.startsAt} onChange={(event) => setOffer('startsAt', event.target.value)} className="mt-1"/></label><label className="text-sm font-semibold">Ends at<Input type="datetime-local" value={offerForm.endsAt} onChange={(event) => setOffer('endsAt', event.target.value)} className="mt-1"/></label><label className="text-sm font-semibold">Display order<Input type="number" value={offerForm.displayOrder} onChange={(event) => setOffer('displayOrder', event.target.value)} className="mt-1"/></label>
      <div className="flex flex-wrap items-end gap-3 text-sm font-semibold"><label className="flex gap-2"><input type="checkbox" checked={offerForm.enabled} onChange={(event) => setOffer('enabled', event.target.checked)}/>Enabled</label><label className="flex gap-2"><input type="checkbox" checked={offerForm.showInOffersPage} onChange={(event) => setOffer('showInOffersPage', event.target.checked)}/>Offers page</label><label className="flex gap-2"><input type="checkbox" checked={offerForm.showInProfile} onChange={(event) => setOffer('showInProfile', event.target.checked)}/>My Offers</label><label className="flex gap-2"><input type="checkbox" checked={offerForm.featured} onChange={(event) => setOffer('featured', event.target.checked)}/>Featured</label></div>
      <div className="flex gap-3 md:col-span-2"><Button type="submit" disabled={busy || !offerForm.imageAssetId}>{busy ? 'Saving…' : editingOffer ? 'Save offer' : 'Create offer'}</Button>{editingOffer && <Button type="button" variant="outline" onClick={() => { setEditingOffer(null); setOfferForm(blankOffer()) }}>Cancel edit</Button>}</div>
    </form></section>
    <section className="mt-6 overflow-x-auto rounded-xl border bg-card"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-3">Offer</th><th>Image</th><th>Coupon</th><th>Placement</th><th>Status</th><th/></tr></thead><tbody>{offers.map((offer) => <tr key={offer.id} className="border-b"><td className="p-3"><b>{offer.title}</b><p className="text-xs text-muted-foreground">/{offer.slug}</p></td><td>{offer.imageUrl ? <img src={offer.imageUrl} alt="" className="h-12 w-20 rounded object-cover"/> : '—'}</td><td>{coupons.find((coupon) => coupon.id === offer.couponId)?.code || '—'}</td><td>{[offer.showOnHomepage && 'Home', offer.showInOffersPage && 'Offers', offer.showInProfile && 'Account'].filter(Boolean).join(', ')}</td><td>{offer.enabled ? 'Enabled' : 'Disabled'}</td><td><Button size="sm" variant="outline" onClick={() => editOffer(offer)}>Edit</Button> <Button size="sm" variant="outline" onClick={() => void remove('offers', offer.id)}>Delete</Button></td></tr>)}</tbody></table></section>
  </main>
}
